### ISSUE TITLE
Regularization term

### ISSUE THREAD

**Issue by JunwenBai** [BouchardLab/DynamicalComponentsAnalysis#45]
According to the predictive information objective, the loss function should be scale-invariant, which means you actually don't need to add a regularization term. But I saw regularization term is still added in the implementation. Could you explain why? Thx!

**Comment by JesseLivezey** [comment]
You're right that analytically the loss function should be scale invariant. In practice, we occasionally saw optimization have numerical problems which can happen if two components of the projection become highly colinear which can make the log-determinant calculation and gradients unstable. Adding this loss fixed those problems.

I think it's better to think about the term as providing numerical conditioning rather than regularization. For a projection Y = V^T X, you can apply any invertible linear transformation, L, within the projected subspace and the loss in invariant, i.e., Y' = L V^T X. So, for any minimum of the Predictive Information loss, you can then descend the 'regularization' term to 0 regularization loss without changing the PI or the subspace found.

**Comment by JunwenBai** [comment]
Got it. Thanks for the quick and clear explanation!
I also noticed that you used Toeplitzification. In practice, I don't see many changes to the cov matrix. But I do know Toeplitz matrix can save computation time in add and multiplications. Is the Toeplitzification mainly for stability concern or computational concern? What if I don't use it?

**Comment by JesseLivezey** [comment]
The toeplitz flag uses a method for calculating log-determinants when the matrices are block-toeplitz. This should give the same result, but be faster in some cases. This can be faster for large T and d. The default setting is to use the heuristic of using the block-toeplitz method when T > 10 and d > 40. It might vary a bit depending on your setup, but it is only a computational difference.

**Comment by JunwenBai** [comment]
Make sense. Thx for providing the heuristics!
